apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: victim-apps
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: ["frontend", "api", "worker"]
  podMetricsEndpoints:
  - port: http
    path: /metrics
